<section class="administration-wrapper p-5">

  <section class="row">
    <div class="col-5 bg-dark px-5 py-2">
      <h2>Dashboard</h2>
      <hr style="background-color:#fff;">
      <h3>Server time: <?php $time = new DateTime("now");
      echo $time->format("H:i:s");?></h3>
      <div class="accordion bg-dark" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
      <h5 class="mb-0">Add</h5>
    </div>
    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body bg-dark d-flex flex-row justify-content-around">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target=".modal-events">Add event</button>
        <button type="button" class="btn btn-success" data-toggle="modal" data-target=".modal-games">Add games</button>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingOne" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseOne">
      <h5 class="mb-0">Edit</h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body bg-dark row justify-content-around">
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target=".modal-edit-games">Edit games</button>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo"  data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
      <h5 class="mb-0">Remove</h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body bg-dark row justify-content-around">
        <button type="button" class="btn btn-danger col-5 m-1" data-toggle="modal" data-target=".modal-remove-event">Remove event</button>
        <button type="submit" class="btn btn-danger col-5 m-1" data-toggle="modal" data-target=".modal-remove-game">Remove game</button>
        <button type="submit" class="btn btn-danger col-5 m-1" data-toggle="modal" data-target=".modal-remove-bracket">Remove bracket</button>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo"  data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseTwo">
      <h5 class="mb-0">Tools</h5>
    </div>
    <div id="collapseFour" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body bg-dark row justify-content-around">
        <button type="button" class="btn btn-warning col-5 m-1" data-toggle="modal" data-target=".modal-verification">Verification tool</button>
      </div>
    </div>
  </div>


</div>
    </div>
    <div class="col-7">
      <div class="log-wrapper bg-dark">
        <div class="d-flex w-80 p-2 ml-2">
          <h3>Logs</h3>
          <button class="btn btn-primary btn-sm ml-3" type="button" name="button">Filtruj ></button>
        </div>
        <table class="table table-dark table-bordered table-sm table-striped table-hover">
    <thead>
      <tr>
        <th scope="col"><a href="#">Log_id &and;</a></th>
        <th scope="col"><a href="#">User_id</a></th>
        <th scope="col"><a href="#">Username</a></th>
        <th scope="col"><a href="#">Type</a></th>
        <th scope="col"><a href="#">Timestamp</a></th>
        <th scope="col"><a href="#">User_ip</a></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($logs as $log): ?>
      <tr class="log-row" data-toggle="modal" data-target=".modal-log-detail" data-logid="<?= $log['log_id']?>">
        <th scope="row"><?= $log['log_id'] ?> </th>
        <td><?= $log['uid'] ?></td>
        <td><?= $log['uname'] ?></td>
        <td><?= $log['log_type'] ?></td>
        <td><?= $log['log_timestamp'] ?></td>
        <td><?= $log['log_userip'] ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
      </div>
        </div>
  </section>



  <div class="modal fade modal-events" tabindex="-1" role="dialog" aria-labelledby="..." aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title">Add an Esport event</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form method="post">
      <input type="hidden" name="event-add">
  <div class="form-group">
  <label for="exampleInputEmail1">Event name</label>
  <input type="text" class="form-control" name="eventName" aria-describedby="emailHelp" placeholder="Enter name">
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;" for="inputGroupSelect01">Game</label>
      </div>
      <select class="custom-select" name="eventGame">
        <?php foreach($games as $game): ?>
        <option value="<?= $game['game_id']?>"><?= $game['game_name'] ?></option>
      <?php endforeach; ?>
      </select>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;" for="inputGroupSelect01">Event Date & Time</label>
        <input class="form-control date-picker mx-1" type="datetime-local" name="eventDate" placeholder="Enter date...">
        <input class="form-control" type="time" name="eventTime" value="">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text bg-success" style="color:#FFF;" for="inputGroupSelect01">Event Playerlimit</label>
          <input class="form-control" type="text" name="eventPL" value="">
        </div>
      </div>
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;" for="inputGroupSelect01">Event Url</label>
        <input class="form-control" type="text" name="eventUrl" value="">
      </div>
    </div>
</div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Add event</button>
    </form>
  </div>
      </div>
    </div>
  </div>
  </div>

  <div class="modal fade modal-games" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title">Add an official event game</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form method="post" enctype="multipart/form-data">
      <input type="hidden" name="game-add">
  <div class="form-group">
  <label for="exampleInputEmail1">Game name</label>
  <input type="text" class="form-control" aria-describedby="emailHelp" placeholder="Enter name" name="mod-gameadd-name">
  </div>
  <div class="form-group">
  <label for="exampleInputEmail1">Game short name (no tabs, spaces, special characters)</label>
  <input type="text" class="form-control" placeholder="Enter name" name="mod-gameadd-shortname">
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text bg-success" style="color:#Fff;">Ruleset</span>
    </div>
    <div class="custom-file">
      <input type="file" class="custom-file-input" name="file-ruleset" aria-describedby="inputGroupFileAddon01">
      <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
    </div>
  </div>
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text bg-success" style="color:#Fff;">Game background</span>
    </div>
    <div class="custom-file">
      <input type="file" class="custom-file-input" name="file-background" aria-describedby="inputGroupFileAddon01">
      <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
    </div>
  </div>
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;">Team limit</label>
      </div>
      <select class="custom-select" name="mod-gameadd-playerlimit">
        <option selected value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
      </select>
    </div>
  </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Add event</button>
    </form>
  </div>
      </div>
    </div>
  </div>

  <div class="modal fade modal-edit-games" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title">Edit a game</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form method="post" enctype="multipart/form-data">
      <input type="hidden" name="game-edit">
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;">Game</label>
      </div>
      <select class="custom-select" name="edit-game-id" onchange="getGameForm(this.value)">
        <option selected>Choose a game...</option>
        <?php foreach ($games as $game): ?>
          <option value="<?=$game['game_id']?>"><?=$game['game_name']?></option>
        <?php endforeach; ?>
      </select>

    </div>
  </div>
        <div class="live-form-game-update"></div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Edit game</button>
    </form>
  </div>
      </div>
    </div>
  </div>

  <div class="modal fade modal-remove-event" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title">Remove event</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form method="post" enctype="multipart/form-data">
      <input type="hidden" name="event-remove">
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;">Event</label>
      </div>
      <select class="custom-select" name="remove-event-id">
        <option selected>Choose an event...</option>
        <?php foreach ($events as $event): ?>
          <option value="<?=$event['event_id']?>"><?=$event['event_name']?></option>
        <?php endforeach; ?>
      </select>
    </div>
  </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Remove event</button>
    </form>
  </div>
      </div>
    </div>
  </div>

  <div class="modal fade modal-remove-game" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title">Remove game</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form method="post" enctype="multipart/form-data">
      <input type="hidden" name="game-remove">
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success">Game</label>
      </div>
      <select class="custom-select" name="remove-game-id">
        <option selected>Choose a game...</option>
        <?php foreach ($games as $game): ?>
          <option value="<?=$game['game_id']?>"><?=$game['game_name']?></option>
        <?php endforeach; ?>
      </select>
    </div>
  </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Remove game</button>
    </form>
  </div>
      </div>
    </div>
  </div>

  <div class="modal modal-log-detail" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title">Log</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body modal-log-detail-body"></div>
      </div>
    </div>
  </div>

  <div class="modal fade modal-verification" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title">Verification tool</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form method="post">
      <input type="hidden" name="user-verification">
      <section class="d-flex flex-row p-2">
        <button class="btn btn-warning" type="button" name="button" onclick="addUserInput()">+</button>
      </section>
      <div class="form-group w-50 mx-auto">
        <div class="user-input-group p-3 mb-3 row">
            <input class="form-control" id="newMessage_username" onkeyup='loadUserLiveText(this.value,"livesearch-verify","hint-verify")' type="text" name="receiver" value="" placeholder="Username#HexId" autocomplete="off">
        </div>
        <div class="livesearch-verify livehint-layout p-3 my-5 text-center justify-content-center align-items-center" style="display: none;">
          <p>Hint:</p>
          <hr>
          <div class="hint-verify"></div>
        </div>
      </div>
  <button type="submit" class="btn btn-secondary" name="button">Verify</button>
</form>
  </div>
      </div>
    </div>
  </div>


</section>
<script src="public/js/administrationmodel.js"></script>
<script>
  $('.date-picker').flatpickr();
</script>
