<section class="events-wrapper">
  <?php if (count($events)): ?>
    <div class="scrollables d-flex flex-column bg-dark p-3">
      <?php foreach ($events as $event): ?>
        <a class="p-2" href="events#event-<?=$event['event_id']?>"><?=$event['event_name']?></a>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>

  <?php if (!count($events)): ?>
    <div class="d-flex justify-content-center align-items-center" style="height:100vh;">
      <div>
      <img src="public/images/soon.gif" alt="" style="border-radius:2rem;">
      </div>

    </div>
  <?php endif; ?>
  <?php foreach($events as $event): ?>
    <article class="event-wrapper pb-5 d-flex justify-content-center align-items-center" id="event-<?=$event['event_id']?>" style="background-image:url(<?=$event['game_background']?>)!important;">
      <section class="eventcard p-5 mx-auto col-9 text-center">
        <a href="events/<?=$event['event_url']?>" style="text-decoration: none; color:#fff;">
          <?php if ($event['event_status'] == "live"): ?>
              <span class="p-1" style="background-color:red;">Live</span>
          <?php endif; ?>
          <?php if ($event['event_status'] == "scheduled"): ?>
              <span class="p-1" style="background-color:orange;">Scheduled</span>
          <?php endif; ?>
          <?php if ($event['event_status'] == "finished"): ?>
              <span class="p-1" style="background-color:blue;">Finished</span>
          <?php endif; ?>

          <h1><?= $event['event_name'] ?></h1>
        <hr style="background-color:#fff">
        <div class="row justify-content-center">
          <h3 class="col-11 m-1"><img src="<?=$event['game_icon']?>" height="50" width="50">  <?= $event['game_name'] ?></h3>
          <h3 class="col-5 m-1"><img src="public/images/i-time.png">  <?= $event['event_parseddate'] ?></h3>
          <h3 class="col-5 m-1"><img src="public/images/i-players.png">  Fixed: <?=$event['player_count']?> / <?= $event['event_playerlimit'] ?></h3>
        </div>
        </a>
        <?php if ($event['event_status'] == "scheduled"): ?>
          <button class="btn btn-success" type="button" name="button" data-toggle="modal" data-target=".modal-event-join" data-eventid="<?=$event['event_id']?>" data-gameid="<?=$event['game_id']?>" data-eventurl="<?=$event['event_url']?>">Join with your team</button>
        <?php endif; ?>
        <?php if ($user['admin'] || $user['watchman'] || $user['rootmaster']): ?>
          <a class="btn btn-danger" href="events/edit/<?=$event['event_url']?>" role="button">Edit event</a>
        <?php endif; ?>
      </section>
    </article>

  <?php endforeach; ?>

  <div class="modal fade modal-editevent" tabindex="-1" role="dialog" aria-labelledby="..." aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title" style="color:#000;" id="exampleModalCenterTitle">Edit an event</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form method="post">
      <input type="hidden" name="event-add">
  <div class="form-group">
  <label for="exampleInputEmail1">Event name</label>
  <input type="text" class="form-control" name="eventName" aria-describedby="emailHelp" placeholder="Enter name">
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;" for="inputGroupSelect01">Game</label>
      </div>
      <select class="custom-select" name="eventGame">
      </select>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;" for="inputGroupSelect01">Event Date & Time</label>
        <input class="form-control date-picker mx-1" type="datetime-local" name="eventDate" placeholder="Enter date...">
        <input class="form-control" type="time" name="eventTime">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text bg-success" style="color:#FFF;" for="inputGroupSelect01">Event Playerlimit</label>
          <input class="form-control" type="text" name="eventPL" value="">
        </div>
      </div>
  </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Add event</button>
    </form>
  </div>
      </div>
    </div>
  </div>
  </div>

  <div class="modal fade modal-event-join" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title">Join an event</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body p-5">
    <form method="post">
      <input type="hidden" name="event-join">
      <input class="event-id-input" type="hidden" name="event-id">
      <input class="game-id-input" type="hidden" name="game-id">
      <input class="event-url-input" type="hidden" name="event-url">
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text bg-success" style="color:#FFF;">Available teams</label>
      </div>
      <select class="custom-select" name="team-id">
        <?php foreach($userTeams as $team): ?>
        <option value="<?= $team['team_id']?>"><?= $team['team_name'] ?></option>
      <?php endforeach; ?>
      </select>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-warning">Join an event</button>
    </form>
  </div>
      </div>
      </div>
    </div>
  </div>
</section>


<script src="public/js/eventsmodel.js"></script>
