<?php foreach($events as $event): ?>
  <article class="event-wrapper pb-5 d-flex justify-content-center align-items-center">

    <section class="eventcard p-5 mx-auto w-75 text-center">
      <h1><?= $event['event_name'] ?></h1>
      <h2><?= $event['game_name'] ?></h2>
      <h3><?= $event['event_parseddate'] ?></h3>
      <h4>Players: 0 / <?= $event['event_playerlimit'] ?></h4>
      <button class="btn btn-success" type="button" name="button">Register a team</button>
      <button class="btn btn-success" type="button" name="button">Join a team</button>
      <?php if ($admin): ?>
          <button class="btn btn-danger" type="button" name="button">Edit event</button>
      <?php endif; ?>
    </section>

  </article>


<?php endforeach; ?>
