<section class="p-5">
  <div class="event-title p-5 text-center">
    <h1><?= $event['event_name'] ?></h1>
    <input class="event-timestamp" type="hidden" value="<?= $event['event_timestamp'] ?>">
    <div class="hodziny py-4">
      <h2 class="timer-countdown"> <img src="public/images/loading.gif" alt="" height="50"> </h2>
    </div>
  </div>

<section class="navevent-wrapper py-2 w-90 mx-auto mb-5">
  <nav>
    <div class="nav nav-pills" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" data-toggle="tab" href="#nav-teams" role="tab" aria-controls="nav-home" aria-selected="true">Teams</a>
      <a class="nav-item nav-link" data-toggle="tab" href="#nav-bracket" role="tab" aria-controls="nav-profile" aria-selected="false">Bracket</a>
      <?php if ($_SESSION['user']['rootmaster'] || $_SESSION['user']['admin']): ?>
        <a class="nav-item nav-link" data-toggle="tab" href="#nav-adminpanel" role="tab" aria-controls="nav-profile" aria-selected="false">Admin</a>
      <?php endif; ?>
    </div>
  </nav>
  <div class="tab-content tab-content-profile p-5" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-teams" role="tabpanel" aria-labelledby="nav-home-tab">
      <section class="team-wrapper d-flex flex-wrap justify-content-around mb-3">
                  <?php foreach ($teams as $team): ?>
        <div class="col-6 my-2">
          <section class="each-team col-12 mx-auto p-4">
          <div>
            <p><?= $team['name'] ?></p>
            <hr style="background-color:orange;">
          </div>
          <ul>
            <?php foreach ($team['players'] as $player): ?>
              <li><?= $player ?></li>
            <?php endforeach; ?>
          </ul>
          </section>
        </div>
      <?php endforeach; ?>


      </section>
    </div>
    <div class="tab-pane fade" id="nav-bracket" role="tabpanel" aria-labelledby="nav-profile-tab">
      <?php if ($hasBrackets): ?>
        <section class="bracket-wrapper text-center d-flex flex-row justify-content-around align-items-center">
          <?php for($i = 0; $i < count($matches); $i++): ?>
            <div class="each-round col-3">
            <?php foreach ($matches[$i] as $match): ?>
                  <div class="eachmatch py-2 mx-1 my-2 row justify-content-center align-items-center">
                    <div class="col-9 d-flex flex-column" style="border-right:1px solid orange;">
                      <p><?php if (isset($match['match_first_team_seed'])):?><?= "(m" . $match['match_first_team_seed'] . ")"?><?php endif; ?> <?php if (isset($match['match_first_team_name'])): ?><?=$match['match_first_team_name']?> <?php endif;?><?php if (!isset($match['match_first_team_name'])): ?><?='freewin/TBD'?> <?php endif;?></p>
                      <p><?php if (isset($match['match_second_team_seed'])):?><?="(m" . $match['match_second_team_seed'] . ")"?><?php endif; ?> <?php if (!isset($match['match_second_team_name'])): ?><?='freewin/TBD'?> <?php endif;?><?php if (isset($match['match_second_team_name'])): ?><?=$match['match_second_team_name']?> <?php endif;?></p>
                    </div>
                    <div class="matchScore col-2 row justify-content-center">
                      <h2 class="col-12"><?= $match['match_first_team_score'] ?></h2>
                      <h2 class="col-12"><?= $match['match_second_team_score'] ?></h2>
                    </div>
                    <?php if ($_SESSION['user']['admin'] || $_SESSION['user']['watchman'] || $_SESSION['user']['rootmaster']): ?>
                      <div class="col-1 m-2">
                        <button class="btn btn-primary" type="button" data-toggle="modal" data-target=".modal-scorewrite">+</button>
                      </div>
                    <?php endif; ?>
                  </div>
            <?php endforeach; ?>
          </div>
        <?php endfor; ?>
        </section>
      <?php endif; ?>
    </div>
    <?php if ($_SESSION['user']['rootmaster'] || $_SESSION['user']['admin']): ?>
      <div class="tab-pane fade" id="nav-adminpanel" role="tabpanel" aria-labelledby="nav-profile-tab">
        <div class="accordion bg-dark" id="accordionExample">
    <div class="card">
      <div class="card-header" id="headingOne" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <h5 class="mb-0">Settings</h5>
      </div>

      <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
        <div class="card-body bg-dark">
          <form method="post">
            <input type="hidden" name="event-add">
        <div class="form-group">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text bg-warning text-dark" style="color:#FFF;" for="inputGroupSelect01">Status</label>
            </div>
            <select class="custom-select" name="eventGame">
                <option value="scheduled">Scheduled</option>
                <option value="live">Live</option>
                <option value="finished">Finished</option>
            </select>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text bg-warning mr-1 text-dark" style="color:#FFF;" for="inputGroupSelect01">Postpone (m)</label>
              <button class="btn btn-small btn-warning" type="button" name="button">+5</button><button class="btn btn-small btn-warning" type="button" name="button">+10</button><button class="btn btn-small btn-warning" type="button" name="button">+15</button><button class="btn btn-small btn-warning" type="button" name="button">+20</button>
              <button class="btn btn-small btn-warning" type="button" name="button">+25</button><button class="btn btn-small btn-warning" type="button" name="button">+30</button>
            </div>
          </div>
          <div class="form-group">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="input-group-text bg-warning text-dark" style="color:#FFF;" for="inputGroupSelect01">Bracket format</label>
                <select class="custom-select" name="eventGame">
                    <option value="scheduled">Single-elimination</option>
                    <option value="live">Double-elimination</option>
                </select>
              </div>
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="input-group-text bg-warning text-dark" style="color:#FFF;" for="inputGroupSelect01">Basic matches format</label>
                <select class="custom-select" name="eventGame">
                    <option value="scheduled">BO1</option>
                    <option value="live">BO3</option>
                    <option value="live">BO5</option>
                </select>
              </div>
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="input-group-text bg-warning text-dark" style="color:#FFF;" for="inputGroupSelect01">Elimination matches format</label>
                <select class="custom-select" name="eventGame">
                    <option value="scheduled">BO1</option>
                    <option value="live">BO3</option>
                    <option value="live">BO5</option>
                </select>
              </div>
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="input-group-text bg-warning text-dark" style="color:#FFF;" for="inputGroupSelect01">Final format</label>
                <select class="custom-select" name="eventGame">
                    <option value="scheduled">BO1</option>
                    <option value="live">BO3</option>
                    <option value="live">BO5</option>
                </select>
              </div>
            </div>
        </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Update</button>
          </form>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingTwo"  data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <h5 class="mb-0">Bracket</h5>
      </div>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div class="card-body bg-dark">
          <span class="bg-danger p-1">Status</span>
          <hr>
          <form method="post">
            <input type="hidden" name="bracket-generate">
            <input type="hidden" name="event-id" value="<?= $event['event_id']?>">
            <div class="row justify-content-around">
              <button class="btn btn-primary" type="submit" name="button">Generate</button>
              <button class="btn btn-danger" type="button" data-toggle="modal" data-target=".dropConfirmationModal">Drop</button>
            </div>

          </form>

        </div>
      </div>
    </div>

  </div>
      </div>
    <?php endif; ?>
  </div>
</section>
<div class="modal dropConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal">
    <div class="modal-content">
      <div class="modal-header">
  <h5 class="modal-title">Confirmation</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body modal-log-detail-body">
  <p>Are you sure?</p>
  <form method="post">
    <button type="submit" name="button">Yes</button>
  </form>
</div>
    </div>
  </div>
</div>

<div class="modal modal-scorewrite" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal">
    <div class="modal-content">
      <div class="modal-header">
  <h5 class="modal-title">Write and confirm a match score</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body modal-log-detail-body">
  <form method="post">
    <input type="text" name="" value="Team1" readonly>
    <input type="text" name="" value="Team2" readonly>
    <input type="number" name="scoreFirstTeam" value="">
    <input type="number" name="scoreSecondTeam" value="">
    <button type="submit" name="button">Confirm</button>
    </form>
</div>
    </div>
  </div>
</div>
</section>

<script src="public/js/eventmodel.js"></script>
