<!-- GameFormStart -->
<input type="hidden" name="game-id" value="<?=$game['game_id']?>">
<div class="form-group">
<label for="exampleInputEmail1">Game name</label>
<input type="text" class="form-control" placeholder="Enter name" name="mod-gameadd-name" value="<?=$gameCur['game_name']?>">
</div>
<div class="form-group">
<label for="exampleInputEmail1">Game short name (no tabs, spaces, special characters)</label>
<input type="text" class="form-control" placeholder="Enter name" name="mod-gameadd-shortname" value="<?=$gameCur['game_short_name']?>">
</div>
<div class="form-group">
<div class="input-group mb-3">
<div class="input-group-prepend">
  <span class="input-group-text bg-success" style="color:#Fff;">Ruleset</span>
</div>
<div class="custom-file">
  <input type="file" class="custom-file-input" name="file-ruleset">
  <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
</div>
</div>
</div>
<div class="form-group">
<div class="input-group mb-3">
<div class="input-group-prepend">
  <span class="input-group-text bg-success" style="color:#Fff;">Game background</span>
</div>
<div class="custom-file">
  <input type="file" class="custom-file-input" name="file-background">
  <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
</div>
</div>
</div>
<div class="form-group">
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <label class="input-group-text bg-success" style="color:#FFF;">Team limit</label>
  </div>
  <select class="custom-select" name="mod-gameadd-playerlimit">
    <option selected value="<?=$gameCur['game_playerlimitperteam']?>"><?=$gameCur['game_playerlimitperteam']?></option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
  </select>
</div>
</div>
<!-- GameFormEnd -->
