<section class="home d-flex flex-column justify-content-center align-items-center">
  <section class="d-flex flex-column justify-content-center align-items-center" style="height:100vh;">
    <div class="pr-5 homesign" style="border-radius: 0 2rem 0 2rem;">
      <img src="public/images/logo_spse_text.png" alt="" width="600" style="border-radius: 0 2rem 0 2rem">
    </div>
    <div class="closeSideNav my-3">
      <a href="https://discord.gg/Xxcdkqw" target="_blank"><img src="public/images/discord.jfif" alt="" height="250" style="border-radius:.7rem;"></a>
    </div>
  </section>
  <section class="d-none d-lg-flex d-lg-flex align-items-center my-5" style="height:100vh;">
    <section id="twitch-embed"></section>
  </section>
</section>

<script src="https://embed.twitch.tv/embed/v1.js"></script>
<script type="text/javascript">
   let embed = new Twitch.Embed("twitch-embed", {
     width: window.screen.availWidth - 200,
     height: window.screen.availHeight - 200,
     channel: "spsegaming",
     layout: "video"
   });
   embed.addEventListener(Twitch.Embed.VIDEO_READY, () => {
  var player = embed.getPlayer();
  player.play();
});
</script>
