<div class="home-wrapper d-flex flex-column justify-content-around pb-md-5 align-items-center">
  <div class="news text-light px-3 text-center">
      <img src="/public/images/logo2.svg" width="350" alt="">
    <h1 class="m-lg-4 m-md-1">Esportový turnaj s letitou tradicí pořádaný žáky SPŠE Pardubice</h1>
    <a href="login" class="btn btn-lg btn-main mr-auto mt-1">Přihlásit se</a>
  </div>
  <div class="social-media d-flex flex-wrap justify-content-around pb-3 align-items-center w-100">
      <div class="social-item m-1">
        <a href="https://discord.gg/yCUmthz"><img src="/public/images/discord.jpg" alt=""></a>
      </div>
      <div class="social-item m-1">
        <a href="twitch.tv/spsegaming"><img src="/public/images/twitch.jpg" alt=""></a>
      </div>
  </div>
</div>

<script type="text/javascript">
document.querySelector("#homeLink").classList.add("nav-links-selected");
</script>
