<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <base href="/spsegamehub.local" />
  <meta charset="utf-8">
  <meta name="keywords" content="<?= $keywords ?>">
  <meta name="description" content="<?= $desc ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?= $title   ?></title>
  <link rel="stylesheet" href="/public/css/master.css">
  <link rel="stylesheet" href="/public/css/bracket.css">
  <link rel="stylesheet" href="/public/css/layering.css">
  <link rel="stylesheet" href="/public/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <link rel="stylesheet" href="/public/css/atom.css">
  <link rel="stylesheet" href="/public/css/slide.css">
  <link rel="stylesheet" href="/public/css/media.css">
  <link rel="icon" href="/public/images/favicon.png">

  <script src="/public/js/jquery.js"></script>
  <script src="/public/js/popper.min.js"></script>
  <script src="/public/js/bootstrap.min.js"></script>
</head>

<body>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-133561856-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-133561856-2');
  </script>

  <div class="toast-wrapper">
    <?php foreach ($messages as $msg) : ?>
      <div class="toast" data-autohide='false'>
        <div class="toast-header bg-red-main text-light">
          <strong class="mr-auto">Upozornění</strong>
          <small class="mx-2"><?= date('G:i') ?></small>
          <button type="button" class="ml-2 mb-1 close text-light" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="toast-body bg-blue-gray" style="color:#fff;">
          <?= $msg ?>
        </div>
      </div>
    <?php endforeach ?>
  </div>

  <nav class="mainnav bg-blue-gray d-flex flex-lg-column flex-md-row justify-content-start">
    <a class="d-flex justify-content-center align-items-center" href="/">
      <div class="text-light hero-top"><img class="hero" src="/public/images/logo2_notext.svg" alt=""></div>
    </a>
    <div class="top-menu d-flex flex-column justify-content-around align-items-center">
      <a class="nav-links p-2 my-1 row justify-content-center align-items-center" id="homeLink" href="home"><img class="mr-1" src="/public/images/i-home.png" width="28" height="28" alt="">
        <h4>Home</h4>
      </a>
      <a class="nav-links p-2 my-1 row justify-content-center align-items-center" id="eventLink" href="events"><img class="mr-1" src="/public/images/i-events.png" width="28" height="28" alt="">
        <h4>Events</h4>
      </a>
      <?php if ($logged) : ?>
        <a class="nav-links p-2 my-1 row justify-content-center align-items-center" id="messagesLink" href="messages"><img class="mr-1" src="/public/images/i-messages.png" width="28" height="28" alt="">
          <h4>Messages</h4>
        </a>
      <?php endif; ?>
      <?php if ($logged && ($user['admin'] || $user['rootmaster'])) : ?>
        <a class="nav-links p-2 my-1 row justify-content-center align-items-center" id="adminLink" href="administration"><img class="mr-1" src="/public/images/i-admin.png" width="28" height="28" alt="">
          <h4>Admin</h4>
        </a>
      <?php endif; ?>
    </div>

    <?php if (!$logged) : ?>
      <div class="button-menu mt-auto mb-3 d-flex flex-column align-items-center justify-content-center text-center">
        <a href="login" class="btn-lg btn-main m-1 w-75">LOGIN</a>
        <a href="register" class="btn-lg btn-main m-1 w-75">REGISTER</a>
      </div>
    <?php endif; ?>
    <?php if ($logged) : ?>
      <div class="profile-menu btn-group mx-auto text-light mt-auto mb-3 text-center dropup">
        <a href="profile" class="btn btn-main">
          <img class="mr-1" src="https://img.icons8.com/ios-filled/20/000000/user.png" /><?= $user['name'] ?>
        </a>
        <button type="button" class="btn btn-main dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu bg-space p-3">
          <div class="d-flex flex-column justify-content-center">
            <a href="profile/logout" class="btn my-1 btn-sm btn-main"><img class="pb-1 pr-1" src="https://img.icons8.com/android/20/000000/logout-rounded-left.png" />Logout</a>
          </div>
        </div>
      </div>
    <?php endif; ?>

    <div class="hamburger ml-auto mr-3 d-flex align-items-center" onclick="toggleNav()">
      <img src="/public/images/hamburger.svg" width="40" alt="">
    </div>
  </nav>

  <div id="myNav" class="overlay">
    <a href="javascript:void(0)" class="closebtn" onclick="toggleNav()">&times;</a>
    <div class="overlay-content text-light">
      <a class="btn m-1 btn-blue-gray w-75 mx-auto" href="home">Home</a>
      <a class="btn m-1 btn-blue-gray w-75 mx-auto" href="events">Events</a>
      <?php if ($logged && ($user['admin'] || $user['rootmaster'])) : ?>
        <a class="btn m-1 btn-blue-gray w-75 mx-auto" href="administration">Admin</a>
      <?php endif; ?>
      <hr class="bg-blue-gray">
      <?php if ($logged) : ?>
        <a class="btn m-1 btn-blue-gray w-75 mx-auto" href="profile"><img class="mr-1" src="https://img.icons8.com/ios-filled/40/000000/user.png" /><?= $user['name'] ?></a>
        <a class="btn m-1 btn-blue-gray w-75 mx-auto" href="profile/logout"><img class="pb-1 pr-1" src="https://img.icons8.com/android/40/000000/logout-rounded-left.png" />logout</a>
      <?php endif; ?>
      <?php if (!$logged) : ?>
        <a class="btn m-1 btn-blue-gray w-75 mx-auto" href="login">Sign in</a>
      <?php endif; ?>
    </div>
  </div>


  <article class="content bg-space">
    <?php $this->controller->showView(); ?>
  </article>


  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="/public/js/pace.min.js"></script>
  <script type="text/javascript" src="public/js/layout.js"></script>
</body>

</html>
