<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="keywords" content="<?= $keywords ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?= $desc ?>">
    <title><?= $title   ?></title>
        <link rel="stylesheet" href="public/css/master.css">
        <link rel="stylesheet" href="public/css/layering.css">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
         crossorigin="anonymous"></script>
         <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
         <script src="public/js/main.js"></script>
         <script src="public/js/live.js"></script>
  </head>
  <body>

    <div style="position:absolute;top:0;right:0; z-index:5;">
  <?php foreach($messages as $msg) : ?>
  <div class="toast bg-dark" style="position: absolute; top: 8vh; right: 10px; z-index:6;" data-autohide='false'>
    <div class="toast-header">
      <strong class="mr-auto">Upozornění</strong>
      <small class="mx-2"><?= date('G:i') ?></small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body" style="color:#fff;">
      <?= $msg ?>
    </div>
  </div>

  <?php endforeach ?>
    </div>

    <article class="content p-5">
      <?php $this->controller->showView(); ?>
    </article>
    <nav class="mainnav navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link ml-5" href="home">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link ml-5" href="#">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link ml-5" href="#">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link ml-5" href="login">Login</a>
      </li>
    </ul>
  </div>
</nav>
  </body>
</html>
