<section class="loginform row justify-content-center align-items-center">
  <form class="w-50" method="POST">
    <div class="form-group">
      <label for="exampleInputEmail1">Email address or Username</label>
      <input type="text" name="name" class="form-control login-input" aria-describedby="emailHelp" placeholder="Enter email or username">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" name="pw" class="form-control login-input" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="">Don't have an account yet? <a href="register">Register</a>.</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</section>
