<!-- MatchStart -->
<form method="post">
  <input type="hidden" name="match-score-write">
  <input class="match-id-input" type="hidden" name="match-id" value="<?=$match['match_id']?>">
  <div class="row justify-content-center p-1 m-1">
    <h2><?= $match['match_first_team_name'] ?></h2>
    <div class="col-2">
      <input class="form-control" type="number" value="<?=$match['match_first_team_score']?>" name="first-score" min="0" max="3">
    </div>
    <h2>:</h2>
    <div class="col-2">
      <input  class="form-control" type="number" value="<?=$match['match_second_team_score']?>" name="second-score" min="0" max="3">
    </div>
    <h2><?= $match['match_second_team_name'] ?></h2>
  </div>
  <div class="p-2 mx-1 my-3">
    <label for="match-status">Match status</label>
    <select class="form-control" name="match-status">
      <option value="<?=$match['match_status']?>" selected><?=$match['match_status']?></option>
      <option value="scheduled">Scheduled</option>
      <option value="live">Live</option>
      <option value="finished">Finished</option>
    </select>
  </div>
  <button class="btn btn-primary" type="submit" name="button">Submit</button>
</form>
<!-- MatchEnd -->
