<!-- MessageStart -->
  <article class="message-wrapper p-1 text-center justify-content-center align-items-center">
    <?php if ($message['message_type'] == "invite"): ?>
        <p><?= $_message['message'] ?></p>
    <?php endif; ?>
    <?php if ($message['message_type'] == "message" || $message['message_type'] == "trash"): ?>
        <p><?= $message['message'] ?></p>
    <?php endif; ?>

    <section class="row justify-content-center align-items-center">
      <?php if ($message['message_type'] == "message"): ?>
        <button class="btn btn-primary mx-1" type="button" name="button">Reply</button>
        <button class="btn btn-primary mx-1" type="button" name="button">Mark as read</button>
        <button class="btn btn-danger mx-1" type="button" name="button">Remove</button>
      <?php endif; ?>
      <?php if ($message['message_type'] == "invite"): ?>
        <form method="post">
          <input type="hidden" name="accept-invite">
          <input type="hidden" name="message-id" value="<?=$message['message_id']?>">
          <input type="hidden" name="team-id" value="<?= $message['invite_team_id'] ?>">
          <button class="btn btn-primary mx-1" type="submit" name="button">Accept invite</button>
        </form>
        <form method="post">
          <input type="hidden" name="decline-invite">
          <input type="hidden" name="message-id" value="<?=$message['message_id']?>">
          <button class="btn btn-danger mx-1" type="submit" name="button">Decline invite</button>
        </form>
      <?php endif; ?>
      <?php if ($message['message_type'] == "trash"): ?>
        <button class="btn btn-danger mx-1" type="submit" name="button">Remove completely</button>
      <?php endif; ?>
    </section>
  </article>
<!-- MessageEnd -->
