<!-- MessageStart -->
  <article class="message-wrapper p-1 text-center justify-content-center align-items-center">
    <p><?= $message['message'] ?></p>
    <section class="row justify-content-center align-items-center">
      <button class="btn btn-primary mx-1" type="button" name="button">Reply</button>
      <button class="btn btn-primary mx-1" type="button" name="button">Mark as read</button>
      <button class="btn btn-danger mx-1" type="button" name="button">Remove</button>
    </section>
  </article>
<!-- MessageEnd -->
