<header class="content-messages px-2 pb-5" id="msgContent">
  <section class="messages-wrapper py-1">
        <?php foreach($messages as $msg): ?>
          <a class="message-a">
          <div class="message row p-5" onclick='loadMessage("<?=$msg['message_id']?>")'>
            <div class="col-3"><?= $msg['user_sendername'] ?></div><div class="col-4"><?= $msg['message'] ?></div><div class="col-3"><?= $msg['message_timestamp'] ?></div><div class="col-2"><img src="https://img.icons8.com/windows/50/000000/reply-arrow.png"></div>
        </div></a><hr>
      <?php endforeach; ?>
  </section>
  <section class="messages-footer justify-content-center align-items-center py-1">
      <button type="button" class="btn btn-danger" onclick='showNewMessage("#new_message")' id="newMessage" name="button" style="border-radius: 25px;"><img src="https://img.icons8.com/color/48/000000/new-message.png"></button>
  </section>

  <div class="new-message p-5 w-50 mx-auto" id='new_message' style="display:none;">
      <button class="close" type="button" name="button" onclick='closeNewMessage("#new_message")'>
        <span>&times;</span>
      </button>
      <form method="post">
        <input type="hidden" name="message-add">
        <div class="form-group w-50">
          <div class="input-group mb-3">
            <div class="input-group-prepend mr-2">
              <label class="input-group-text bg-success" style="color:#FFF;">Receiver</label>
            </div>
            <div class="row">
              <input class="form-control" id="newMessage_username" onkeyup='loadUserLiveText(this.value)' type="text" name="receiver" value="" placeholder="Username#HexId" autocomplete="off">
            </div>
                <div id="livesearch" class="livesearch p-3 my-1 text-center justify-content-center align-items-center"></div>
          </div>
        </div>
    <div class="form-group">
      <div class="input-group mb-3">
        <textarea class="form-control" id="textA" name="message" rows="8" cols="80"></textarea>
      </div>
    </div>
    <button type="submit" class="btn btn-secondary" name="button">Send</button>
  </form>
    </div>


<script>
  if (typeof profile == 'undefined') {
    window.location.replace('profile');
  }
</script>
</header>
