<section class="profile-wrapper p-5 text-center justify-content-center align-items-center">
  <div class="profile-img">
    <img src="public/images/bernie.jpg" alt="" style="border-radius: 10rem;" height="250">
  </div>
  <div class="py-3">
    <h2><?= $user['name'] ?><span style="color:rgba(255,255,255,.7);">#<?= $user['user_hexid']; ?></span></h2>
    <h2><?= $user['email'] ?></h2>
    <?php if ($user['rootmaster']): ?>
      <div class="my-3">
        <span class="admin-tag p-2 ">Rootmaster</span>
      </div>
    <?php endif; ?>
    <?php if ($user['admin']): ?>
      <div class="my-3">
        <span class="admin-tag p-2 ">Admin</span>
      </div>
    <?php endif; ?>
    <?php if ($user['watchman']): ?>
      <div class="my-3">
        <span class="admin-tag p-2 ">Watchman</span>
      </div>
    <?php endif; ?>
  </div>

  <section class="navevent-wrapper py-2 w-90 mx-auto">
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Teams</a>
        <a class="nav-item nav-link" data-toggle="tab" href="#nav-friends" role="tab" aria-controls="nav-profile" aria-selected="false">Friends</a>
      </div>
    </nav>
    <div class="tab-content p-5 bg-dark" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">Teamy</div>
      <div class="tab-pane fade" id="nav-friends" role="tabpanel" aria-labelledby="nav-profile-tab">Kamaradi</div>
    </div>
  </section>
</section>

<script src="public/js/profilemodel.js"></script>
