<section class="profile-wrapper p-5 text-center">
  <div class="profile-info col-5 mx-auto p-3">
    <div class="profile-img">
      <img src="public/images/bernie.jpg" alt="" style="border-radius: 10rem;" height="250">
    </div>
    <div class="py-3">
      <h2><?php if ($user['user_verified'] == 1): ?>
        <img src="https://img.icons8.com/ios-glyphs/30/000000/verified-account--v2.png">
      <?php endif; ?><?= $user['name'] ?><span style="color:rgba(255,255,255,.7);">#<?= $user['user_hexid']; ?></span></h2>
      <h2><?= $user['email'] ?></h2>
      <?php if ($user['rootmaster']): ?>
        <div class="my-3">
          <span class="admin-tag p-2 ">Rootmaster</span>
        </div>
      <?php endif; ?>
      <?php if ($user['admin']): ?>
        <div class="my-3">
          <span class="admin-tag p-2 ">Admin</span>
        </div>
      <?php endif; ?>
      <?php if ($user['watchman']): ?>
        <div class="my-3">
          <span class="admin-tag p-2 ">Watchman</span>
        </div>
      <?php endif; ?>
    </div>
  </div>


  <section class="navevent-wrapper py-2 w-90 mx-auto mb-5">
    <nav>
      <div class="nav nav-pills" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" data-toggle="tab" href="#nav-teams" role="tab" aria-controls="nav-home" aria-selected="true">Teams</a>
        <!--<a class="nav-item nav-link" data-toggle="tab" href="#nav-friends" role="tab" aria-controls="nav-profile" aria-selected="false">Friends</a> -->
      </div>
    </nav>
    <div class="tab-content tab-content-profile p-5" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-teams" role="tabpanel">
        <?php if (!$hasTeams): ?>
          <p>User has no teams...</p>
          <button class="btn btn-warning" type="button" name="button" data-toggle="modal" data-target=".modal-team-add">Create a team</button>
        <?php endif; ?>
        <?php if ($hasTeams): ?>
          <section class="team-wrapper d-flex flex-wrap justify-content-around mb-3">
          <?php foreach ($userTeams as $team): ?>
            <div class="col-4 mb-3">
              <section class="each-team col-12 mx-auto p-4"data-toggle="modal" data-target=".modal-team-detail" onclick="loadTeamDetail('<?=$team['id']?>')">
              <div>
                <p><?= $team['name'] ?><span class="game-name ml-2" style="color:#3C3B3F;">(<img class="mx-1" src="<?=$team['game_icon']?>" alt="" height="20">)</span></p>
                <hr style="background-color:orange;">
              </div>
              <ul>
                <?php for ($i = 0; $i < count($team['players']); $i++): ?>
                    <li><?= $team['players'][$i]  ?></li>
                <?php endfor; ?>
              </ul>
              </section>
            </div>

          <?php endforeach; ?>
          </section>
          <hr>
          <?php if (count($userTeams) < 5): ?>
            <button class="btn btn-warning" type="button" name="button" data-toggle="modal" data-target=".modal-team-add">Create a team</button>
          <?php endif; ?>
        <?php endif; ?>
      </div>
      <div class="tab-pane fade" id="nav-friends" role="tabpanel">Kamaradi</div>
    </div>
  </section>
</section>

<div class="modal modal-team-detail" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content modal-content-team-preview"></div>
    </div>
  </div>

  <?php if (count($userTeams) < 5): ?>
    <div class="modal modal-team-add fade" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
      <h5 class="modal-title">Create a team</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body p-5">
      <form method="post">
        <input type="hidden" name="team-add">
    <div class="form-group">
    <label for="exampleInputEmail1">Team name</label>
    <input type="text" class="form-control" name="teamName" placeholder="Hustaci">
    </div>
    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text bg-success" style="color:#FFF;">Game</label>
        </div>
        <select class="custom-select" name="teamGame">
          <?php foreach($games as $game): ?>
          <option value="<?= $game['game_id']?>"><?= $game['game_name'] ?></option>
        <?php endforeach; ?>
        </select>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-warning">Create a team</button>
      </form>
    </div>
        </div>
        </div>
      </div>
    </div>
  <?php endif; ?>



<script src="public/js/profilemodel.js"></script>
