<section class="loginform d-flex justify-content-center align-items-center">
  <form class="w-50" method="POST">
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" name="email" class="form-control login-input" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Username</label>
      <input type="text" name="usrname" class="form-control login-input" aria-describedby="emailHelp" placeholder="Enter username">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" name="pw" class="form-control login-input" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password again</label>
      <input type="password" name="pwA" class="form-control login-input" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Please enter the current year</label>
      <input type="text" name="antispam" class="form-control login-input" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="">Already have an account? <a href="login">Login</a>.</label>
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">I agree with the <a href="tos">terms of service</a></label>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

</section>
